# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test BobApp Front

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  FrontEnd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front 

    steps:
    - name : Checkout
      uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name : Install dependencies Angular
      run: npm install

    - name : Test run with coverage
      run: npm run test:prod
      
    - name: Upload coverage report as a workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: karma-report
        path: front/coverage
